title: Dimitris Palyvos Giannas
url: ""
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/dmpalyvos"
footer_text: "Dimitris Palyvos Giannas"

sass:
    style: compressed
    sass_dir: _sass

plugins:
    - jekyll-redirect-from

whitelist:
    - jekyll-redirect-from
