# Setup
title:               Dimitris Palyvos
tagline:             'Tuple by tuple'
description:         ''
url:                 https://palyvos.net
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dimitris Palyvos-Giannas
  url:               https://palyvos.net
  email:             blog@palyvos.net

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
