title: Researcher
url: ""
baseurl: "/home"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/dmpalyvos"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass
